// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package psql

import (
	"context"
)

const getExpense = `-- name: GetExpense :one
SELECT id, name FROM expenses 
WHERE id=$1 LIMIT 1
`

func (q *Queries) GetExpense(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i Expense
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
