// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package psql

import (
	"context"
)

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT id, name from expenses
`

func (q *Queries) GetAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseById = `-- name: GetExpenseById :one
SELECT id, name FROM expenses 
WHERE id=$1 LIMIT 1
`

func (q *Queries) GetExpenseById(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseById, id)
	var i Expense
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
