// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package psql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToExpense = `-- name: AddTagToExpense :exec
INSERT INTO expenses_tags (expense_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToExpenseParams struct {
	ExpenseID int64
	TagID     int64
}

func (q *Queries) AddTagToExpense(ctx context.Context, arg AddTagToExpenseParams) error {
	_, err := q.db.Exec(ctx, addTagToExpense, arg.ExpenseID, arg.TagID)
	return err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (name, amount, cost)
VALUES ($1, $2, $3)
RETURNING id, name, amount, cost, item_id, is_deleted, created_at, updated_at
`

type CreateExpenseParams struct {
	Name   string
	Amount pgtype.Numeric
	Cost   pgtype.Numeric
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense, arg.Name, arg.Amount, arg.Cost)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Cost,
		&i.ItemID,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, is_deleted
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT id, name, amount, cost, item_id, is_deleted, created_at, updated_at from expenses
`

func (q *Queries) GetAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Cost,
			&i.ItemID,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
SELECT id, name, created_at, updated_at, is_deleted
FROM tags
WHERE is_deleted = false
ORDER BY name
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpend = `-- name: GetDailySpend :many
SELECT created_at::date AS day, COALESCE(SUM(amount), 0)::DECIMAL(10,3) AS total
FROM expenses
WHERE is_deleted = false
  AND created_at >= (date_trunc('month', CURRENT_TIMESTAMP) - ($1::int || ' months')::interval)
GROUP BY created_at::date
ORDER BY day
`

type GetDailySpendRow struct {
	Day   pgtype.Date
	Total pgtype.Numeric
}

func (q *Queries) GetDailySpend(ctx context.Context, months int32) ([]GetDailySpendRow, error) {
	rows, err := q.db.Query(ctx, getDailySpend, months)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySpendRow
	for rows.Next() {
		var i GetDailySpendRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpendForMonth = `-- name: GetDailySpendForMonth :many
SELECT created_at::date AS day, COALESCE(SUM(amount), 0)::DECIMAL(10,3) AS total
FROM expenses
WHERE is_deleted = false
  AND EXTRACT(YEAR FROM created_at) = $1::int
  AND EXTRACT(MONTH FROM created_at) = $2::int
GROUP BY created_at::date
ORDER BY day
`

type GetDailySpendForMonthParams struct {
	Year  int32
	Month int32
}

type GetDailySpendForMonthRow struct {
	Day   pgtype.Date
	Total pgtype.Numeric
}

func (q *Queries) GetDailySpendForMonth(ctx context.Context, arg GetDailySpendForMonthParams) ([]GetDailySpendForMonthRow, error) {
	rows, err := q.db.Query(ctx, getDailySpendForMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySpendForMonthRow
	for rows.Next() {
		var i GetDailySpendForMonthRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseById = `-- name: GetExpenseById :one
SELECT id, name, amount, cost, item_id, is_deleted, created_at, updated_at FROM expenses 
WHERE id=$1 LIMIT 1
`

func (q *Queries) GetExpenseById(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseById, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Cost,
		&i.ItemID,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpensesByMonth = `-- name: GetExpensesByMonth :many
SELECT id, name, amount, cost, item_id, is_deleted, created_at, updated_at
FROM expenses
WHERE is_deleted = false
  AND EXTRACT(YEAR FROM created_at) = $1::int
  AND EXTRACT(MONTH FROM created_at) = $2::int
ORDER BY created_at
`

type GetExpensesByMonthParams struct {
	Year  int32
	Month int32
}

func (q *Queries) GetExpensesByMonth(ctx context.Context, arg GetExpensesByMonthParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getExpensesByMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Cost,
			&i.ItemID,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstExpenseDate = `-- name: GetFirstExpenseDate :one
SELECT COALESCE(TO_CHAR(MIN(created_at::date), 'YYYY-MM-DD'), '') AS first_date
FROM expenses
WHERE is_deleted = false
`

func (q *Queries) GetFirstExpenseDate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getFirstExpenseDate)
	var first_date interface{}
	err := row.Scan(&first_date)
	return first_date, err
}

const getTagsForExpense = `-- name: GetTagsForExpense :many
SELECT t.id, t.name, t.created_at, t.updated_at, t.is_deleted
FROM tags t
JOIN expenses_tags et ON t.id = et.tag_id
WHERE et.expense_id = $1 AND t.is_deleted = false
ORDER BY t.name
`

func (q *Queries) GetTagsForExpense(ctx context.Context, expenseID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsForExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSpendThisMonth = `-- name: GetTotalSpendThisMonth :one
SELECT COALESCE(SUM(amount), 0)::DECIMAL(10,3) AS total
FROM expenses
WHERE is_deleted = false
  AND created_at >= date_trunc('month', CURRENT_TIMESTAMP)
`

func (q *Queries) GetTotalSpendThisMonth(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalSpendThisMonth)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const removeTagFromExpense = `-- name: RemoveTagFromExpense :exec
DELETE FROM expenses_tags
WHERE expense_id = $1 AND tag_id = $2
`

type RemoveTagFromExpenseParams struct {
	ExpenseID int64
	TagID     int64
}

func (q *Queries) RemoveTagFromExpense(ctx context.Context, arg RemoveTagFromExpenseParams) error {
	_, err := q.db.Exec(ctx, removeTagFromExpense, arg.ExpenseID, arg.TagID)
	return err
}
