// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package psql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToExpense = `-- name: AddTagToExpense :exec
INSERT INTO expenses_tags (expense_id, tag_id)
SELECT $1::bigint, $2::bigint
WHERE EXISTS (SELECT 1 FROM expenses WHERE id = $1::bigint AND user_id = $3::bigint AND is_deleted = false)
  AND EXISTS (SELECT 1 FROM tags WHERE id = $2::bigint AND user_id = $3::bigint AND is_deleted = false)
ON CONFLICT DO NOTHING
`

type AddTagToExpenseParams struct {
	ExpenseID int64
	TagID     int64
	UserID    int64
}

func (q *Queries) AddTagToExpense(ctx context.Context, arg AddTagToExpenseParams) error {
	_, err := q.db.Exec(ctx, addTagToExpense, arg.ExpenseID, arg.TagID, arg.UserID)
	return err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (name, amount, cost, recurrence_interval, recurrence_day, recurrence_start_date, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, amount, cost, item_id, is_deleted, created_at, updated_at, recurrence_interval, recurrence_day, recurrence_start_date, user_id
`

type CreateExpenseParams struct {
	Name                string
	Amount              pgtype.Numeric
	Cost                pgtype.Numeric
	RecurrenceInterval  pgtype.Text
	RecurrenceDay       pgtype.Int4
	RecurrenceStartDate pgtype.Date
	UserID              int64
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Name,
		arg.Amount,
		arg.Cost,
		arg.RecurrenceInterval,
		arg.RecurrenceDay,
		arg.RecurrenceStartDate,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Cost,
		&i.ItemID,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecurrenceInterval,
		&i.RecurrenceDay,
		&i.RecurrenceStartDate,
		&i.UserID,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, user_id)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at, is_deleted, user_id
`

type CreateTagParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, first_name, last_name, email) VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password, avatar_url, first_name, last_name, email, created_at, updated_at
`

type CreateUserParams struct {
	Username  string
	Password  string
	FirstName string
	LastName  string
	Email     string
}

type CreateUserRow struct {
	ID        int64
	Username  string
	Password  string
	AvatarUrl string
	FirstName string
	LastName  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AvatarUrl,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT id, name, amount, cost, item_id, is_deleted, created_at, updated_at, recurrence_interval, recurrence_day, recurrence_start_date, user_id FROM expenses
WHERE user_id=$1 AND is_deleted = false
`

func (q *Queries) GetAllExpenses(ctx context.Context, userID int64) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Cost,
			&i.ItemID,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecurrenceInterval,
			&i.RecurrenceDay,
			&i.RecurrenceStartDate,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
SELECT id, name, created_at, updated_at, is_deleted, user_id
FROM tags
WHERE is_deleted = false AND user_id = $1
ORDER BY name
`

func (q *Queries) GetAllTags(ctx context.Context, userID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getAllTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpend = `-- name: GetDailySpend :many
SELECT created_at::date AS day, COALESCE(SUM(amount), 0)::DECIMAL(10,3) AS total
FROM expenses
WHERE is_deleted = false
  AND user_id = $1::bigint
  AND created_at >= (date_trunc('month', CURRENT_TIMESTAMP) - ($2::int || ' months')::interval)
GROUP BY created_at::date
ORDER BY day
`

type GetDailySpendParams struct {
	UserID int64
	Months int32
}

type GetDailySpendRow struct {
	Day   pgtype.Date
	Total pgtype.Numeric
}

func (q *Queries) GetDailySpend(ctx context.Context, arg GetDailySpendParams) ([]GetDailySpendRow, error) {
	rows, err := q.db.Query(ctx, getDailySpend, arg.UserID, arg.Months)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySpendRow
	for rows.Next() {
		var i GetDailySpendRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpendForMonth = `-- name: GetDailySpendForMonth :many
SELECT created_at::date AS day, COALESCE(SUM(amount), 0)::DECIMAL(10,3) AS total
FROM expenses
WHERE is_deleted = false
  AND user_id = $1::bigint
  AND EXTRACT(YEAR FROM created_at) = $2::int
  AND EXTRACT(MONTH FROM created_at) = $3::int
GROUP BY created_at::date
ORDER BY day
`

type GetDailySpendForMonthParams struct {
	UserID int64
	Year   int32
	Month  int32
}

type GetDailySpendForMonthRow struct {
	Day   pgtype.Date
	Total pgtype.Numeric
}

func (q *Queries) GetDailySpendForMonth(ctx context.Context, arg GetDailySpendForMonthParams) ([]GetDailySpendForMonthRow, error) {
	rows, err := q.db.Query(ctx, getDailySpendForMonth, arg.UserID, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySpendForMonthRow
	for rows.Next() {
		var i GetDailySpendForMonthRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseById = `-- name: GetExpenseById :one
SELECT id, name, amount, cost, item_id, is_deleted, created_at, updated_at, recurrence_interval, recurrence_day, recurrence_start_date, user_id FROM expenses
WHERE id=$1 AND user_id=$2 AND is_deleted = false
LIMIT 1
`

type GetExpenseByIdParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetExpenseById(ctx context.Context, arg GetExpenseByIdParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseById, arg.ID, arg.UserID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Cost,
		&i.ItemID,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecurrenceInterval,
		&i.RecurrenceDay,
		&i.RecurrenceStartDate,
		&i.UserID,
	)
	return i, err
}

const getExpensesByMonth = `-- name: GetExpensesByMonth :many
SELECT id, name, amount, cost, item_id, is_deleted, created_at, updated_at, recurrence_interval, recurrence_day, recurrence_start_date, user_id
FROM expenses
WHERE is_deleted = false
  AND user_id = $1::bigint
  AND EXTRACT(YEAR FROM created_at) = $2::int
  AND EXTRACT(MONTH FROM created_at) = $3::int
ORDER BY created_at
`

type GetExpensesByMonthParams struct {
	UserID int64
	Year   int32
	Month  int32
}

func (q *Queries) GetExpensesByMonth(ctx context.Context, arg GetExpensesByMonthParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getExpensesByMonth, arg.UserID, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Cost,
			&i.ItemID,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecurrenceInterval,
			&i.RecurrenceDay,
			&i.RecurrenceStartDate,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstExpenseDate = `-- name: GetFirstExpenseDate :one
SELECT COALESCE(TO_CHAR(MIN(created_at::date), 'YYYY-MM-DD'), '') AS first_date
FROM expenses
WHERE is_deleted = false AND user_id = $1
`

func (q *Queries) GetFirstExpenseDate(ctx context.Context, userID int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, getFirstExpenseDate, userID)
	var first_date interface{}
	err := row.Scan(&first_date)
	return first_date, err
}

const getTagsForExpense = `-- name: GetTagsForExpense :many
SELECT t.id, t.name, t.created_at, t.updated_at, t.is_deleted, t.user_id
FROM tags t
JOIN expenses_tags et ON t.id = et.tag_id
JOIN expenses e ON e.id = et.expense_id
WHERE et.expense_id = $1
  AND e.user_id = $2
  AND t.user_id = $2
  AND t.is_deleted = false
ORDER BY t.name
`

type GetTagsForExpenseParams struct {
	ExpenseID int64
	UserID    int64
}

func (q *Queries) GetTagsForExpense(ctx context.Context, arg GetTagsForExpenseParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsForExpense, arg.ExpenseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSpendThisMonth = `-- name: GetTotalSpendThisMonth :one
SELECT COALESCE(SUM(amount), 0)::DECIMAL(10,3) AS total
FROM expenses
WHERE is_deleted = false
  AND user_id = $1
  AND created_at >= date_trunc('month', CURRENT_TIMESTAMP)
`

func (q *Queries) GetTotalSpendThisMonth(ctx context.Context, userID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalSpendThisMonth, userID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, avatar_url, first_name, last_name, email, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	ID        int64
	Username  string
	Password  string
	AvatarUrl string
	FirstName string
	LastName  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AvatarUrl,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeTagFromExpense = `-- name: RemoveTagFromExpense :exec
DELETE FROM expenses_tags
WHERE expense_id = $1::bigint AND tag_id = $2::bigint
  AND EXISTS (SELECT 1 FROM expenses WHERE id = $1::bigint AND user_id = $3::bigint)
`

type RemoveTagFromExpenseParams struct {
	ExpenseID int64
	TagID     int64
	UserID    int64
}

func (q *Queries) RemoveTagFromExpense(ctx context.Context, arg RemoveTagFromExpenseParams) error {
	_, err := q.db.Exec(ctx, removeTagFromExpense, arg.ExpenseID, arg.TagID, arg.UserID)
	return err
}

const softDeleteExpense = `-- name: SoftDeleteExpense :execrows
UPDATE expenses
SET is_deleted = true,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type SoftDeleteExpenseParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExpense, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET name = $3,
    amount = $4,
    cost = $5,
    recurrence_interval = $6,
    recurrence_day = $7,
    recurrence_start_date = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND is_deleted = false
RETURNING id, name, amount, cost, item_id, is_deleted, created_at, updated_at, recurrence_interval, recurrence_day, recurrence_start_date, user_id
`

type UpdateExpenseParams struct {
	ID                  int64
	UserID              int64
	Name                string
	Amount              pgtype.Numeric
	Cost                pgtype.Numeric
	RecurrenceInterval  pgtype.Text
	RecurrenceDay       pgtype.Int4
	RecurrenceStartDate pgtype.Date
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.Cost,
		arg.RecurrenceInterval,
		arg.RecurrenceDay,
		arg.RecurrenceStartDate,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Cost,
		&i.ItemID,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecurrenceInterval,
		&i.RecurrenceDay,
		&i.RecurrenceStartDate,
		&i.UserID,
	)
	return i, err
}
